export const some = {
    id: "9dea9bdd-a624-4b5c-ad78-d0128c4d8241",
    therapeuticArea: "oncology",
    trialIdentifier: "111",
    trialPhase: "phase1",
    status: "completed",
    primaryDrugs: "drugA",
    otherDrugs: "",
    title: "111",
    diseaseType: "diabetes",
    patientSegment: "",
    lineOfTherapy: "",
    referenceLinks: "",
    trialTags: "",
    sponsorCollaborators: "sponsorA",
    sponsorFieldOfActivity: "",
    associatedCRO: "",
    countries: "",
    region: "",
    trialRecordStatus: "",
    purposeOfTheTrial:
        "Percentage of Participants Progression-free at 9 Months Based on Response Evaluation Criteria In Solid Tumors v1.1 (RECIST v1.1",
    summary: "",
    primaryOutcomeMeasure:
        "Progression-free at 9 Months Based on Response Evaluation Criteria In Solid Tumors",
    otherOutcomeMeasure: "",
    studyDesignKeywords: "studyDesignKeywords",
    studyDesign: "",
    treatmentRegimen: "",
    numberOfArms: "",
    inclusionCriteria: "",
    exclusionCriteria: "",
    ageFrom: "",
    ageTo: "",
    subjectType: "",
    targetNoOfVolunteers: "",
    sex: "",
    healthyVolunteers: "",
    actualEnrolledVolunteers: "",
    startDateActual: "08/16/2013",
    inclusionPeriodActual: "68.4",
    enrollmentClosedDateActual: "05/10/2019",
    primaryOutcomeDurationActual: "",
    trialEndDateActual: "",
    resultPublishedDateActual: "10/13/2021",
    startDateBenchmark: "",
    inclusionPeriodBenchmark: "",
    enrollmentClosedDateBenchmark: "",
    primaryOutcomeDurationBenchmark: "",
    trialEndDateBenchmark: "",
    resultPublishedDateBenchmark: "",
    startDateEstimated: "",
    inclusionPeriodEstimated: "",
    enrollmentClosedDateEstimated: "",
    primaryOutcomeDurationEstimated: "",
    trialEndDateEstimated: "",
    resultPublishedDateEstimated: "",
    overallDurationToComplete: "20.1",
    overallDurationToPublishResult: "02/10/2020",
    timingReference: "Baseline up to 9 months",
    resultsAvailable: "false",
    endpointsMet: "false",
    adverseEventsReported: "false",
    trialOutcome: "some",
    trialOutcomeReference: "lorem ipsum dolor sit amet",
    trialOutcomeReferenceLink: "",
    trialOutcomeReferenceAttachments: "",
    trialResults: "",
    adverseEventReported: "",
    adverseEventType: "",
    treatmentForAdverseEvents: "",
    totalNoOfSites: "100",
    sitesNotes: "",
    trialChangesLog: "",
    trialAddedDate: "",
    lastModifiedDate: "",
    lastModifiedUser: "",
    fullReviewUser: "",
    fullReview: "false",
    nextReviewDate: "",
    logsNotes: "",
    pipelineData: "",
    pressRelease: "",
    publications: "PubMed",
    trialRegistries: "",
    associatedStudies: "",
};
